steps:
  # Docker イメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-northeast1-docker.pkg.dev/$PROJECT_ID/study-claude-ai-chat/app:$COMMIT_SHA',
        '-t',
        'asia-northeast1-docker.pkg.dev/$PROJECT_ID/study-claude-ai-chat/app:latest',
        '.',
      ]

  # Docker イメージを Artifact Registry にプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/study-claude-ai-chat/app:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/study-claude-ai-chat/app:latest']

  # Cloud Run にデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'study-claude-ai-chat'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/study-claude-ai-chat/app:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '1'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest,ANTHROPIC_API_KEY=ANTHROPIC_API_KEY:latest'

images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/study-claude-ai-chat/app:$COMMIT_SHA'
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/study-claude-ai-chat/app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

timeout: '1200s'
